services:
  - type: web
    name: Minha-Biblioteca
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn biblioteca_pai.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: biblioteca_pai.settings
